import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve('.');
const LOCK_FILE = path.join(ROOT, 'package-lock.json');
const OUT_FILE = path.join(ROOT, 'THIRD-PARTY-LICENSES.txt');

const LICENSE_FILE_NAMES = [
  'LICENSE', 'LICENSE.md', 'LICENSE.txt',
  'LICENCE', 'LICENCE.md', 'LICENCE.txt',
  'LICENSE-MIT', 'COPYING', 'COPYING.md',
];

interface LockEntry {
  version?: string;
  dev?: boolean;
  license?: string;
}

interface Manifest {
  version?: string;
  homepage?: string;
  license?: string | { type?: string };
  licenses?: Array<string | { type?: string }>;
  author?: string | { name?: string; email?: string };
}

interface Pkg {
  name: string;
  version: string;
  license: string;
  author: string;
  homepage: string;
  text: string;
}

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, 'utf8')) as T;
}

function readManifest(dir: string): Manifest {
  try {
    return readJson<Manifest>(path.join(dir, 'package.json'));
  } catch {
    return {};
  }
}

function licenseId(entry: LockEntry, manifest: Manifest): string {
  if (entry.license) return entry.license;
  const lic = manifest.license;
  if (typeof lic === 'string') return lic;
  if (lic && lic.type) return lic.type;
  const lics = manifest.licenses;
  if (lics && lics.length) {
    const joined = lics
      .map((l) => (typeof l === 'string' ? l : l.type ?? ''))
      .filter(Boolean)
      .join(', ');
    if (joined) return joined;
  }
  return 'UNKNOWN';
}

function authorString(manifest: Manifest): string {
  const a = manifest.author;
  if (!a) return '';
  if (typeof a === 'string') return a;
  return [a.name, a.email ? `<${a.email}>` : ''].filter(Boolean).join(' ');
}

function licenseText(dir: string): string {
  for (const name of LICENSE_FILE_NAMES) {
    const file = path.join(dir, name);
    if (fs.existsSync(file)) {
      try {
        const text = fs.readFileSync(file, 'utf8').trim();
        if (text) return text;
      } catch {
      }
    }
  }
  return '';
}

function collectPackages(): Pkg[] {
  const lock = readJson<{ packages?: Record<string, LockEntry> }>(LOCK_FILE);
  const packages = lock.packages ?? {};
  const seen = new Set<string>();
  const result: Pkg[] = [];

  for (const [key, entry] of Object.entries(packages)) {
    if (key === '' || entry.dev) continue;
    const marker = 'node_modules/';
    const at = key.lastIndexOf(marker);
    if (at === -1) continue;
    const name = key.slice(at + marker.length);
    const dir = path.join(ROOT, key);
    const manifest = readManifest(dir);
    const version = entry.version ?? manifest.version ?? '0.0.0';
    const id = `${name}@${version}`;
    if (seen.has(id)) continue;
    seen.add(id);
    result.push({
      name,
      version,
      license: licenseId(entry, manifest),
      author: authorString(manifest),
      homepage: manifest.homepage ?? '',
      text: licenseText(dir),
    });
  }

  return result.sort((a, b) => a.name.localeCompare(b.name));
}

function render(pkgs: Pkg[]): string {
  const sep = '='.repeat(78);
  const rule = '-'.repeat(78);
  const header = [
    'THIRD-PARTY SOFTWARE LICENSES',
    '',
    'Yobi bundles the open-source packages listed below. Each remains under its',
    'own license, reproduced here as required for redistribution.',
    `Packages: ${pkgs.length}. Generated by scripts/generate-licenses.ts.`,
    '',
    sep,
    '',
  ].join('\n');

  const body = pkgs.map((p) => {
    const meta = [`${p.name}@${p.version}`, `License: ${p.license}`];
    if (p.author) meta.push(`Author: ${p.author}`);
    if (p.homepage) meta.push(`Homepage: ${p.homepage}`);
    const text = p.text || '(No bundled license file; see SPDX identifier above.)';
    return `${meta.join('\n')}\n\n${text}\n\n${rule}\n`;
  }).join('\n');

  return `${header}${body}`;
}

function main(): void {
  const pkgs = collectPackages();
  fs.writeFileSync(OUT_FILE, render(pkgs), 'utf8');
  console.log(`✅ Wrote ${path.relative(ROOT, OUT_FILE)} (${pkgs.length} packages)`);
}

try {
  main();
} catch (err: unknown) {
  console.error('❌ License generation failed:', err);
  process.exit(1);
}
